name: Test C Task Runner Distroless

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install KraftKit
        run: |
          curl -sSfL https://get.kraftkit.sh | sudo DEBIAN_FRONTEND=noninteractive sh -s -- -y

      - name: Build Unikernel
        working-directory: examples/task-runner-c1.0-distroless
        run: kraft build --plat qemu --arch x86_64 .

      - name: Measure RootFS Size
        working-directory: examples/task-runner-c1.0-distroless
        run: |
          du -sh .unikraft/build/ || true
          find .unikraft/build/ -type f -name "*.img" -exec du -h {} + || true

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "fs"
          scan-ref: "examples/task-runner-c1.0-distroless"
          format: "table"
          exit-code: "0"
          severity: "CRITICAL,HIGH"

      - name: Install QEMU and Grant Permissions
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-x86
          sudo chmod 666 /dev/kvm

      - name: Run and Validate Output
        working-directory: examples/task-runner-c1.0-distroless
        run: |
          output=$(timeout 30s kraft run --rm -M 128M 2>&1 || true)

          echo "$output"

          echo "$output" | grep -q "ADD(10, 32) = 42"
          echo "$output" | grep -q "FIB(10) = 55"
          echo "$output" | grep -q "SQUARE(7) = 49"
          echo "$output" | grep -q "Completed: 3 tasks."